# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1a79df8057d648396f70acb0dae9670f3cc29ed0f342a2e2042a72d084e378531116f83b77fe85c2615ec7c263675814b9e67ee8264f07af369e3e883c4d242

test:
  secret_key_base: 23499810e452d355e47e7f020fafea857b7073539f5a84c9b52db300f66c1e8568a804898719ce74f3c2a6f9a4f171b6d114f6526ad485cd2639ba6d6a112711

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
